from uuid import uuid4


def generate_mock_response(message: str) -> str:
    return (
        f'I received your message: "{message}". '
        "This response is being streamed from the Flask backend "
        "using Server-Sent Events."
    )


def split_into_chunks(text: str):
    words = text.split()

    for word in words:
        yield word + " "



def generate_mock_response(message: str) -> str:
    return (
        f'I received your message: "{message}". '
        "Here is a response generated by the Flask backend. "
    )


def split_into_chunks(text: str):
    words = text.split()

    for word in words:
        yield word + " "


def build_ui_component(message: str):
    lower_message = message.lower()

    if "restaurant" in lower_message:
        return {
            "id": str(uuid4()),
            "type": "info_card",
            "props": {
                "title": "Bella Italia",
                "description": (
                    "A popular Italian restaurant "
                    "in downtown Vancouver."
                ),
                "rating": 4.7,
            },
        }

    if "food" in lower_message:
        return {
            "id": str(uuid4()),
            "type": "quick_replies",
            "props": {
                "options": [
                    "Italian",
                    "Japanese",
                    "Persian",
                ]
            },
        }

    return None